### ISSUE TITLE
Schema DataFiled type 'timestamp'

### ISSUE THREAD

**Issue by weasel2k** [codename-hub/php-parquet#17]
Is there anything I can do for creating parquet file that will be used in time related queries. It seems Timestamp is not available?

Not a major issue but also bigint?

**Comment by Katalystical** [comment]
What about using DateTimeDataField?
You can also fall back to using Longs/Ints if you're aiming for pure Unix Timestamp-ish ones. Internally, its stored as milli/microseconds, depending on what you define.
BigInt/arbitrary precision/length depends a little bit, its the Decimal type you're probably looking for.

**Comment by weasel2k** [comment]
Thank you for response, appreciated

`$schema = new Schema([
  DataField::createFromType('makerid', 'string'),
  DataField::createFromType('coresymbol', 'string'),
  DataField::createFromType('timerecorded', 'DateTime'),
]);`

resulted in
`PHP type/class 'DateTime' is not supported, please specify one of 'object, string, boolean, string, , , , , , integer, , integer, double, double, string, array, , , ' or use an alternative constructor/static creation method`

Is the supported data types listed in documentation?

**Comment by Katalystical** [comment]
As I mentioned, use **DateTimeDataField**.
