### ISSUE TITLE
can't append rows in a existed parquet file

### ISSUE THREAD

**Issue by billjazz** [codename-hub/php-parquet#18]
public function __construct($handle, Schema $schema, ?ParquetOptions $options = null)
  {
    $append = false; // TODO: detect already written data and change to true (append mode)
    $this->schema = $schema;
    $this->writerInstance = new ParquetWriter($schema, $handle, $options, $append);
  }

expecting the append

**Comment by Katalystical** [comment]
Could you please elaborate?
